name: githubaction
on: push
env:
  PRINT_GOOD_BYE: False
#  GITHUB_TOKEN: ${{ github.token }}

  GITHUB_TOKEN: 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
  DOCKER_IMAGE_NAME: ghcr.io/asheesh-amg/test-github-action/flask_test
  DOCKER_IMAGE_VERSION: 2.7
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World! $PRINT_GOOD_BYE"
      - name: Print goodbye
        if: ${{ env.PRINT_GOOD_BYE == 'True'}}
        run: echo "Done - bye!"
      - name: Check out the code
        uses: actions/checkout@v3
      - name: run command
        run: ls -lrt
      - name: Authenticalte github packages service
        run: docker login https://ghcr.io -u asheesh-amg -p $GITHUB_TOKEN
      - name: Build docker image
        run: docker build -f Dockerfile -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_VERSION .
      - name: push the docker image
        run: docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_VERSION
